// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujoirmojetkdqiohwdon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqb2lybW9qZXRrZHFpb2h3ZG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTE1NDcsImV4cCI6MjA3MDMyNzU0N30.R6uacrpXnOxhALCe3dyfs-i1q4x-ocP9zvT80WYkAYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});